services:
  - type: web
    name: alex-fortuna
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: alex-fortuna-db
          property: connectionString

databases:
  - name: alex-fortuna-db
    databaseName: alex_fortuna
    user: alex_fortuna
